"use client";

import { CalendarDays, Check, Clock3, ShieldCheck, UserRound } from "lucide-react";
import { useEffect, useState } from "react";

type Employee = { id: string; name: string; role: string; status: "Aktiv" | "På ferie"; initials: string; hours: string; absence?: string };
const demo: Employee[] = [
  { id: "emp-1", name: "Peter Hartz Jensen", role: "Synsinspektør", status: "Aktiv", initials: "PH", hours: "Man–fre · 08:00–16:20" },
  { id: "emp-2", name: "Rasmus Havn Mourtizen", role: "Teknisk ansvarlig / Ejer", status: "Aktiv", initials: "RH", hours: "Man–fre · 07:30–16:30" },
  { id: "emp-3", name: "Pernille Havn Mouritzen", role: "Bogholder / blæksprut", status: "Aktiv", initials: "PM", hours: "Man–tor · 08:00–15:30" },
];

export function EmployeesView({ onNotify }: { onNotify: (message: string) => void }) {
  const [employees, setEmployees] = useState(demo);
  const [editingEmployee, setEditingEmployee] = useState<Employee | null>(null);
  const [tab, setTab] = useState<"people" | "hours" | "absence">("people");
  const [absenceForm, setAbsenceForm] = useState({ employeeId: "emp-1", kind: "Ferie", dateFrom: "", dateTo: "", note: "" });
  const [absences, setAbsences] = useState<Array<{ id: string; employeeId: string; kind: string; dateFrom: string; dateTo: string; note?: string }>>([]);
  const [workTimes, setWorkTimes] = useState<Record<string, { start: string; end: string; working: boolean }>>(() => { const fallback = { Mandag: { start: "08:00", end: "16:20", working: true }, Tirsdag: { start: "08:00", end: "16:20", working: true }, Onsdag: { start: "08:00", end: "16:20", working: true }, Torsdag: { start: "08:00", end: "16:20", working: true }, Fredag: { start: "08:00", end: "16:20", working: true } }; if (typeof window === "undefined") return fallback; try { return JSON.parse(localStorage.getItem("mb-work-times") ?? "") || fallback; } catch { return fallback; } });
  useEffect(() => { void fetch("/api/employees").then((response) => response.ok ? response.json() : null).then((data) => { if (data?.absences) setAbsences(data.absences.map((item: { id: string; employee_id: string; kind: string; date_from: string; date_to: string; note?: string }) => ({ id: item.id, employeeId: item.employee_id, kind: item.kind, dateFrom: item.date_from, dateTo: item.date_to, note: item.note }))); }).catch(() => undefined); }, []);
  const saveAbsence = async () => { if (!absenceForm.dateFrom || !absenceForm.dateTo) { onNotify("Vælg både fra- og til-dato"); return; } const response = await fetch("/api/employees", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type: "absence", ...absenceForm }) }); if (!response.ok) { onNotify("Fraværet kunne ikke gemmes"); return; } const data = await response.json() as { id: string }; setAbsences((current) => [...current, { id: data.id, ...absenceForm }]); setAbsenceForm((current) => ({ ...current, dateFrom: "", dateTo: "", note: "" })); onNotify("Ferie/fravær er gemt"); };
  const saveEmployee = async () => { if (!editingEmployee) return; const response = await fetch("/api/employees", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type: "employee_update", employeeId: editingEmployee.id, displayName: editingEmployee.name, role: editingEmployee.role, active: editingEmployee.status === "Aktiv" }) }); if (!response.ok) { onNotify("Medarbejderen kunne ikke gemmes"); return; } setEmployees((current) => current.map((item) => item.id === editingEmployee.id ? editingEmployee : item)); setEditingEmployee(null); onNotify("Medarbejderen er opdateret"); };
  const saveWorkTimes = async () => { const days = Object.entries(workTimes); await Promise.all(days.map(([, value], index) => fetch("/api/employees", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type: "work_rule", employeeId: "emp-1", weekday: index + 1, startsAt: value.start, endsAt: value.end, working: value.working }) }))); localStorage.setItem("mb-work-times", JSON.stringify(workTimes)); onNotify("Arbejdstiderne er gemt"); };
  const active = employees.filter((employee) => employee.status === "Aktiv").length;
  return <div className="module-view employees-view">
    <section className="page-heading"><div><p className="eyebrow">Administration · Bemanding</p><h1>Medarbejdere</h1><p>Styr roller, arbejdstider, ferie og fravær samlet ét sted.</p></div><button className="primary-button" onClick={() => onNotify("Ny medarbejder oprettes i næste trin")}>+ Ny medarbejder</button></section>
    <div className="employee-tabs"><button className={tab === "people" ? "selected" : ""} onClick={() => setTab("people")}><UserRound size={15} /> Medarbejdere</button><button className={tab === "hours" ? "selected" : ""} onClick={() => setTab("hours")}><Clock3 size={15} /> Arbejdstider</button><button className={tab === "absence" ? "selected" : ""} onClick={() => setTab("absence")}><CalendarDays size={15} /> Ferie og fravær</button></div>
    <section className="employee-summary"><div><span>Medarbejdere</span><strong>{employees.length}</strong></div><div><span>Aktive i dag</span><strong>{active}</strong></div><div><span>Fravær denne uge</span><strong>{employees.length - active}</strong></div></section>
    {tab === "people" && <section className="employee-card"><div className="employee-table-head"><span>Navn</span><span>Rolle</span><span>Arbejdstid</span><span>Status</span><span></span></div>{employees.map((employee) => <article className="employee-row" key={employee.id}><span className="employee-name"><i>{employee.initials}</i><strong>{employee.name}</strong></span><span>{employee.role}</span><span>{employee.hours}</span><em className={employee.status === "Aktiv" ? "active" : "away"}>{employee.status}</em><button className="secondary-button" onClick={() => setEditingEmployee(employee)}>Rediger</button></article>)}{editingEmployee && <div className="employee-edit"><input value={editingEmployee.name} onChange={(event) => setEditingEmployee({ ...editingEmployee, name: event.target.value })} /><input value={editingEmployee.role} onChange={(event) => setEditingEmployee({ ...editingEmployee, role: event.target.value })} /><select value={editingEmployee.status} onChange={(event) => setEditingEmployee({ ...editingEmployee, status: event.target.value as Employee["status"] })}><option>Aktiv</option><option>På ferie</option></select><button className="primary-button" onClick={() => void saveEmployee()}>Gem ændringer</button><button className="secondary-button" onClick={() => setEditingEmployee(null)}>Annuller</button></div>}</section>}
    {tab === "hours" && <section className="employee-card schedule-card"><h2>Faste arbejdstider og fridage</h2><p>Ændringerne bruges som grundlag for fremtidig bemandings- og bookingkontrol.</p>{Object.entries(workTimes).map(([day, times]) => <div className="schedule-row" key={day}><strong>{day}</strong><span><input type="time" value={times.start} disabled={!times.working} onChange={(event) => setWorkTimes((current) => ({ ...current, [day]: { ...current[day], start: event.target.value } }))} /> – <input type="time" value={times.end} disabled={!times.working} onChange={(event) => setWorkTimes((current) => ({ ...current, [day]: { ...current[day], end: event.target.value } }))} /></span><label><input type="checkbox" checked={times.working} onChange={(event) => setWorkTimes((current) => ({ ...current, [day]: { ...current[day], working: event.target.checked } }))} /> Arbejdsdag</label></div>)}<div className="schedule-row day-off"><strong>Lørdag / søndag</strong><span>Fast fridag</span><Check size={16} /></div><button className="primary-button" onClick={() => void saveWorkTimes()}>Gem arbejdstider</button></section>}
    {tab === "absence" && <section className="employee-card absence-card"><h2>Ferie og fravær</h2><p>Planlagt fravær vises samlet og kan senere bruges direkte i kapacitetsberegningen.</p><div className="absence-form"><select value={absenceForm.employeeId} onChange={(event) => setAbsenceForm((current) => ({ ...current, employeeId: event.target.value }))}>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select><select value={absenceForm.kind} onChange={(event) => setAbsenceForm((current) => ({ ...current, kind: event.target.value }))}><option>Ferie</option><option>Sygdom</option><option>Andet fravær</option></select><input type="date" value={absenceForm.dateFrom} onChange={(event) => setAbsenceForm((current) => ({ ...current, dateFrom: event.target.value }))} /><input type="date" value={absenceForm.dateTo} onChange={(event) => setAbsenceForm((current) => ({ ...current, dateTo: event.target.value }))} /><input placeholder="Note (valgfri)" value={absenceForm.note} onChange={(event) => setAbsenceForm((current) => ({ ...current, note: event.target.value }))} /><button className="primary-button" onClick={() => void saveAbsence()}>Gem fravær</button></div>{absences.map((absence) => { const employee = employees.find((item) => item.id === absence.employeeId); return <article key={absence.id}><span className="employee-avatar">{employee?.initials ?? ""}</span><div><strong>{employee?.name ?? "Medarbejder"}</strong><small>{absence.kind} · {absence.dateFrom} – {absence.dateTo}</small></div></article>; })}</section>}
    <section className="settings-note"><ShieldCheck size={18} /><div><strong>Adgang styres af roller</strong><p>Administratorer kan ændre medarbejdere og fravær. Synsinspektører får kun de funktioner, de skal bruge.</p></div></section>
  </div>;
}
