"use client";

import { Check, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";

type InvoiceStatus = "Klargøres" | "Klar til Dinero" | "APPROVED" | "requires_action";
type Invoice = { id: string; customer: string; period: string; description: string; quantity: number; price: number; status: InvoiceStatus; registration: string; checks?: Array<{ severity: "error" | "warning" | "info"; message: string }> };
const demo: Invoice[] = [
  { id: "inv-1", customer: "Autogården", period: "Juli 2026", description: "Syn · 1. Syn / P-syn · Syns nr. 166869 · Reg. nr. EC20464 · SUZUKI BALENO", quantity: 1, price: 380, status: "Klargøres", registration: "EC20464" },
  { id: "inv-2", customer: "Autohuset", period: "Juli 2026", description: "Syn · 1. Syn / P-syn · Syns nr. 167023 · Reg. nr. EH67875 · OPEL Crossland X", quantity: 1, price: 380, status: "Klar til Dinero", registration: "EH67875" },
  { id: "inv-3", customer: "Bbc Biler", period: "Juli 2026", description: "Syn · Omsyn · Syns nr. 167356 · Reg. nr. CN72849 · SUZUKI VITARA", quantity: 1, price: 380, status: "Klar til Dinero", registration: "CN72849" },
];

export function InvoiceView({ onNotify }: { onNotify: (message: string) => void }) {
  const [invoices, setInvoices] = useState(demo);
  const [loading, setLoading] = useState(true);
  const [selectedId, setSelectedId] = useState(demo[0].id);
  const [reason, setReason] = useState("");
  const selected = invoices.find((invoice) => invoice.id === selectedId) ?? invoices[0];
  const update = (changes: Partial<Invoice>) => setInvoices((current) => current.map((invoice) => invoice.id === selected.id ? { ...invoice, ...changes } : invoice));
  const total = invoices.reduce((sum, invoice) => sum + invoice.quantity * invoice.price, 0);
  useEffect(() => { fetch("/api/invoices", { cache: "no-store" }).then((response) => response.ok ? response.json() as Promise<{ invoices: Array<{ id: string; customer_name: string; period: string; description: string; quantity: number; unit_price_ore: number; status: InvoiceStatus; checks?: Invoice["checks"] }> }> : Promise.reject()).then((data) => setInvoices(data.invoices.map((invoice) => ({ id: String(invoice.id), customer: invoice.customer_name, period: invoice.period, description: invoice.description, quantity: invoice.quantity, price: invoice.unit_price_ore / 100, status: invoice.status, registration: "", checks: invoice.checks })))).catch(() => undefined).finally(() => setLoading(false)); }, []);
  const save = async (changes: Partial<Invoice>) => { if (!selected) return; const next = { ...selected, ...changes }; const response = await fetch("/api/invoices", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: next.id, description: next.description, quantity: next.quantity, unitPriceOre: Math.round(next.price * 100), status: next.status, reason: reason || undefined }) }); if (!response.ok) { onNotify("Fakturaen kunne ikke gemmes — tilføj en begrundelse ved rettelser"); return; } update(changes); setReason(""); onNotify("Fakturaændringen er gemt"); };
  const approve = async () => { if (!selected) return; const response = await fetch("/api/invoices/approve", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ids: [Number(selected.id)] }) }); if (!response.ok) { const data = await response.json().catch(() => ({})); onNotify(data.error ?? "Fakturaen kan ikke godkendes endnu"); return; } update({ status: "APPROVED" }); onNotify("Fakturaen er godkendt og låst til senere Dinero-overførsel"); };
  if (loading) return <div className="module-view invoice-view"><p className="eyebrow">Økonomi · Fakturaklargøring</p><h1>Fakturering</h1><p>Indlæser fakturaklargøring…</p></div>;
  if (!selected) return <div className="module-view invoice-view"><h1>Fakturering</h1><p>Der er ingen fakturaer i klargøring endnu.</p></div>;
  return <div className="module-view invoice-view">
    <section className="page-heading"><div><p className="eyebrow">Økonomi · Fakturaklargøring</p><h1>Fakturering</h1><p>Gennemgå og ret fakturaer, før de sendes videre til Dinero.</p></div><span className="integration-badge"><i /> Dinero ikke aktiveret</span></section>
    <div className="invoice-toolbar"><div className="month-tabs">{["Januar", "Februar", "Marts", "April", "Maj", "Juni", "Juli", "August", "September"].map((month) => <button key={month} className={month === "Juli" ? "selected" : ""}>{month}</button>)}</div><div className="year-tabs"><button>2025</button><button className="selected">2026</button></div></div>
    <section className="invoice-summary"><div><span>Fakturaer i klargøring</span><strong>{invoices.length}</strong></div><div><span>Samlet ekskl. moms</span><strong>{total.toLocaleString("da-DK", { minimumFractionDigits: 2 })} kr.</strong></div><div><span>Status</span><strong className="summary-ok"><i /> Klar til gennemgang</strong></div></section>
    <div className="invoice-layout"><aside className="invoice-customers"><h2>Erhvervskunder</h2>{invoices.map((invoice) => <button key={invoice.id} className={invoice.id === selectedId ? "selected" : ""} onClick={() => setSelectedId(invoice.id)}><span>{invoice.customer}</span><small>{invoice.status}</small><Check size={15} /></button>)}</aside><section className="invoice-editor"><div className="invoice-editor-head"><div><span>Faktura · {selected.period}</span><h2>{selected.customer}</h2></div><em className={selected.status === "Klar til Dinero" || selected.status === "APPROVED" ? "ready" : "draft"}>{selected.status === "APPROVED" ? "Godkendt" : selected.status}</em></div>{selected.checks && selected.checks.length > 0 && <div className="invoice-checks">{selected.checks.map((check, index) => <span className={check.severity} key={`${check.message}-${index}`}>{check.message}</span>)}</div>}<div className="invoice-line-head"><span>Beskrivelse</span><span>Antal</span><span>Pris</span><span>Total inkl. moms</span></div><div className="invoice-line"><label><span>Beskrivelse</span><textarea value={selected.description} onChange={(event) => update({ description: event.target.value })} /></label><input type="number" min="1" value={selected.quantity} onChange={(event) => update({ quantity: Number(event.target.value) })} /><label className="price-field"><input type="number" min="0" value={selected.price} onChange={(event) => update({ price: Number(event.target.value) })} /><span>kr.</span></label><strong>{(selected.quantity * selected.price * 1.25).toLocaleString("da-DK", { minimumFractionDigits: 2 })} kr.</strong></div><label className="invoice-reason">Begrundelse ved rettelse<input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Fx aftalt pris med kunden" /></label><div className="invoice-editor-foot"><span><ShieldCheck size={16} /> Godkendte fakturaer låses og sendes ikke automatisk endnu</span><button className="secondary-button" disabled={selected.status === "APPROVED"} onClick={() => void save({ status: "Klar til Dinero" })}><Check size={15} /> Markér klar til Dinero</button><button className="primary-button" disabled={selected.status === "APPROVED"} onClick={() => void approve()}><Check size={15} /> Godkend</button></div></section></div>
    <button className="secondary-button" onClick={() => void save({ description: selected.description, quantity: selected.quantity, price: selected.price, status: selected.status })}>Gem ændringer</button>
  </div>;
}
